"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer: 4613732

"""

total = 0

val_a = 1
val_b = 2
val_c = 0

while val_a < 4000000:
    val_c = val_a + val_b
    val_a = val_b
    val_b = val_c
    if (val_a % 2 == 0):
        total = total + val_a

print("The sum is {}".format(total))
